// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJopHMTHG22SpEYaI0QIRKD3qFjwbC5EI',
    appId: '1:189748391236:web:19a6c0f6c518a61982fb11',
    messagingSenderId: '189748391236',
    projectId: 'ptune-13a98',
    authDomain: 'ptune-13a98.firebaseapp.com',
    storageBucket: 'ptune-13a98.firebasestorage.app',
    measurementId: 'G-NL35FTZ6CH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsxw14aIUXu1yxMcyciTrujYc-M7JDjGk',
    appId: '1:189748391236:android:2d76cca8d5d5830382fb11',
    messagingSenderId: '189748391236',
    projectId: 'ptune-13a98',
    storageBucket: 'ptune-13a98.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPIeDVbgOhljM_HuMFhC6HcKmJ4I-XbR8',
    appId: '1:189748391236:ios:5fca1f4a5f7cbbc882fb11',
    messagingSenderId: '189748391236',
    projectId: 'ptune-13a98',
    storageBucket: 'ptune-13a98.firebasestorage.app',
    androidClientId:
        '189748391236-9rot5tpveidnpp716vrfqn9f5094teki.apps.googleusercontent.com',
    iosClientId:
        '189748391236-j42s9o1n94o40143mlrrapbe9uci3aru.apps.googleusercontent.com',
    iosBundleId: 'net.getperf.ptune',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPIeDVbgOhljM_HuMFhC6HcKmJ4I-XbR8',
    appId: '1:189748391236:ios:5fca1f4a5f7cbbc882fb11',
    messagingSenderId: '189748391236',
    projectId: 'ptune-13a98',
    storageBucket: 'ptune-13a98.firebasestorage.app',
    androidClientId:
        '189748391236-9rot5tpveidnpp716vrfqn9f5094teki.apps.googleusercontent.com',
    iosClientId:
        '189748391236-j42s9o1n94o40143mlrrapbe9uci3aru.apps.googleusercontent.com',
    iosBundleId: 'net.getperf.ptune',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJopHMTHG22SpEYaI0QIRKD3qFjwbC5EI',
    appId: '1:189748391236:web:8ef261176a9bf8e682fb11',
    messagingSenderId: '189748391236',
    projectId: 'ptune-13a98',
    authDomain: 'ptune-13a98.firebaseapp.com',
    storageBucket: 'ptune-13a98.firebasestorage.app',
    measurementId: 'G-GK23TPJS9T',
  );
}
